--  Generated by Aquarius/Options
package Hera.Options is

   function Scenario return String;
   function Language return String;
   function Randomise return Boolean;
   function Random_Seed return Natural;
   function Batch_Mode return Boolean;
   function Update_Count return Natural;
   function Create return Boolean;
   function Log_Folder return String;
   function Import_Properties return Boolean;
   function Work_Task_Count return Positive;
   function Player_Corporation return String;

end Hera.Options;
